import Head from "next/head";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";

export default function Home() {
  const router = useRouter();

  function handleSubmit(e) {
    e.preventDefault();
    let hotspotAddress = e.target[0].value;
    router.push({
      pathname: `hotspot/${hotspotAddress}`,
    });
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Hotspot lookup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <form onSubmit={handleSubmit}>
        <input
          type="text"
          name="hotspotAddress"
          placeholder="Enter your address"
          id="hotspotAddress"
        />
        <button type="submit">Search</button>
      </form>
    </div>
  );
}
